backend:
  name: github
  repo: resiliocraft-ctrl/resilio-website
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Products"
    folder: "data/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Product Name", name: "name", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
